export JAVA_HOME=`/System/Library/Frameworks/JavaVM.framework/Versions/A/Commands/java_home -v "1.8"`
export ANDROID_HOME="${HOME}/Library/Android/sdk/platform-tools"
export COMMAND_HOME="${HOME}/.commands"
export NODE="${HOME}/.nodebrew/current/bin"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="/usr/local/sbin:$PATH"
export PATH="$COMMAND_HOME:${JAVA_HOME}/bin:$ANDROID_HOME:$NODE:$PYENV_ROOT:$PYENV_ROOT/shims:~/data/local/bin:${HOME}/bin:/usr/local/bin:$PATH"

alias ll='ls -al'
